### ISSUE TITLE
Mobile menu disappeared

### ISSUE THREAD

**Issue by marcelstoer** [justintadlock/stargazer#64]
This is a duplicate of https://wordpress.org/support/topic/menu-missing-on-mobile-device/ and https://wordpress.org/support/topic/mobile-menu-disappeared-4/.

I'm not seeing the mobile menu on https://www.evwe.ch. 

Not sure if this project is still alive.

**Comment by justintadlock** [comment]
This is an issue of the Jetpack plugin overwriting theme front end class styles.

**Comment by justintadlock** [comment]
Sorry, I didn't mean to close the ticket. Leaving open to build in a workaround at some point.

**Comment by marcelstoer** [comment]
I now activated the Jetpack mobile theme to work around this issue. However, it's really just that - a work-around. That mobile theme has other issues one needs to compensate for.

**Comment by navjotjsingh** [comment]
Add this CSS to your child stylesheet.
```

.screen-reader-text.font-secondary {
        clip-path: none !important;
        position: inherit !important;
        height: inherit !important;
}
```

Maybe someone can improve upon this. But as of now, this workaround does brings back the menu.

**Comment by navjotjsingh** [comment]
Find the fix from here: https://themehybrid.com/board/topics/responsive-menu-vanishes

**Comment by marcelstoer** [comment]
@justintadlock @navjotjsingh 

I finally dug into this again and I ended up using the following code borrowed from that board post (I can't seem to comment there any longer)

```css
@media only screen and (max-width: 1024px) {

    .ltr #menu-primary .menu-toggle button,
    .ltr #menu-secondary .menu-toggle button {
        /* use 0.5rem instead of 1.5rem to center it */
        margin: 10px 0 10px 0.5rem;
        position: relative !important;
        height: auto;
        width: auto;
        clip: initial;
        clip-path: none;
        overflow: visible;
    }

    .ltr #menu-primary .menu-toggle button {
        width: 30px;
        height: 28px;
        overflow: hidden;
        /* would otherwise be invisible on webkit */
        -webkit-clip-path: none;
    }

    .ltr #menu-secondary .menu-toggle button {
        margin: 10px 25px 10px 1.5rem;
        background-color: #bea9a9;
        color: #000000;
        padding-right: 12px;
    }
}
```

-> note that I had to add `-webkit-clip-path: none;` as the hamburger icon would otherwise be invisible in Safari i.e. webkit browsers.
